server:
    port: 8081

spring:
    cloud: 
        config:
            server:
                git:
                    default-label:  main
                    uri: https://github.com/bnarvaez2/microservices-practice
                    search-paths:
                    - config-data
    application:
        name: config-services

